## Q1: Create a variable with size [3, 6]

In [1]:
import numpy as np
data1=np.random.rand(3,6)
data1

array([[0.20878243, 0.74506497, 0.19055446, 0.19124601, 0.21508858,
        0.51217203],
       [0.07165594, 0.06434835, 0.78767065, 0.32950642, 0.01789232,
        0.02135339],
       [0.49925055, 0.94891049, 0.04126883, 0.12970189, 0.83155253,
        0.57072468]])

## Q2. Create a variable with normal data size [2, 4] with mu = 5 and sd = 2
variance = ?

In [0]:
data2=np.random.normal(5,2,(2,4))
data2

array([[6.49533957, 1.51433779, 6.50185651, 4.14032899],
       [4.19778158, 8.5745109 , 1.75933267, 3.24958921]])

In [0]:
np.var(data2)

5.347083325095235

In [2]:
data_new = 2*np.random.randn(2, 4) + 5
data_new

array([[6.42902348, 4.10229479, 4.63232589, 7.35657731],
       [3.05517896, 6.20622537, 3.350542  , 6.86790271]])

In [3]:
np.var(data_new)

2.4354586402340823

## Q3. How to provide a copy of the data rather than just a view

In [0]:
data3=data2.copy()
data3

## Indexing & Slicing - 1D
### Q:Select the first element

In [0]:
data4=np.arange(10)
print(data4)
print(data4[0])

[0 1 2 3 4 5 6 7 8 9]
0


## ndarray - Transposing & Swapping Axes
Q. Are you creating a copy or view?

Q. Check what .T will do on high dimensional data?

Q. Try data_3d.swapaxes(1,2)


In [0]:
data = np.arange(15).reshape((3, 5))  
print(data.T)
data_3d = np.arange(16).reshape((2, 2, 4))  # accepts a tuple of axis
print(data_3d.transpose((1, 0, 2)))


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [0]:
data_3d.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [0]:
data_3d.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## ndarray - Unique
For 1-D ndarrays. returns the sorted unique values in an array 

In [0]:
data_ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(data_ints))

[1 2 3 4]


In [0]:
data_ints2 = np.array([[1,2,3,4],[2,1,3,4,],[1,2,3,4],[1,2,3,4],[2,1,3,4],[3,3,3,1,1]])
print(np.unique(data_ints2))

[list([1, 2, 3, 4]) list([2, 1, 3, 4]) list([3, 3, 3, 1, 1])]


In [0]:
import pandas as pd
ser=pd.Series([10,20,30,40])
print(ser)
print(ser.values)
print(ser.index)

0    10
1    20
2    30
3    40
dtype: int64
[10 20 30 40]
RangeIndex(start=0, stop=4, step=1)


In [0]:
data22 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df2=pd.DataFrame(data22)
print(df2)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9


In [0]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)
print(obj['b'])
print(obj[1])
print(obj.drop(['d', 'c']))

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
1.0
1.0
a    0.0
b    1.0
e    4.0
dtype: float64


In [0]:
data33 = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])  
print(data33)
print(data33.iloc[2])
print('+++')
print(data33.iloc[2, [3, 0, 1]])


          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
one       8
two       9
three    10
four     11
Name: Utah, dtype: int64
+++
four    11
one      8
two      9
Name: Utah, dtype: int64


In [0]:
print(data33.iloc[0,3])
print('+++')
print(data33.iloc[1,[1,2,0]])

3
+++
two      5
three    6
one      4
Name: Colorado, dtype: int64


In [0]:
df3 = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])  
print(df3)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3


用于查看数据框头部 5 行或者尾部 5 行的数据。你也可以传入数字指定查看的行数。

In [0]:
print(df3.sum())
print(df3.head())
print(df3.tail())

one    9.25
two   -5.80
dtype: float64
    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
