# Instructions for Assignment 1



1.   All the submissions should be attempted individually.
1.   Please submit the assignment either on **mycources** or mail directly to arbaaz.khan@mail.mcgill.ca
2.   You have the option of either submitted the python notebook (.ipynb) or in .pdf format
1.   Maximum points associated with this assignment = 15.







# 1 Numpy 

## 1.1 Create an *empty* numpy array of size [3, 8]
[1 point]

In [1]:
import numpy as np
data1=np.random.rand(3,8)
print(data1)

[[0.90066106 0.47532933 0.07441738 0.09170602 0.44569308 0.0354568
  0.67182156 0.76341784]
 [0.89925988 0.64679544 0.81405398 0.8639188  0.27183229 0.53112839
  0.12009203 0.28071156]
 [0.21828294 0.97125952 0.41999511 0.79552887 0.97345253 0.84001435
  0.54882495 0.28309142]]


## 1.2 Check the size and data type of the array
[1 point]

In [2]:
print(data1.shape)
print(data1.dtype)

(3, 8)
float64


## 1.3 Assign the value of 6 to the element at row= 2 and column = 7
[1 point]

In [3]:
data1[1,6]=6
data1

array([[0.90066106, 0.47532933, 0.07441738, 0.09170602, 0.44569308,
        0.0354568 , 0.67182156, 0.76341784],
       [0.89925988, 0.64679544, 0.81405398, 0.8639188 , 0.27183229,
        0.53112839, 6.        , 0.28071156],
       [0.21828294, 0.97125952, 0.41999511, 0.79552887, 0.97345253,
        0.84001435, 0.54882495, 0.28309142]])

In [4]:
print(data1)

[[0.90066106 0.47532933 0.07441738 0.09170602 0.44569308 0.0354568
  0.67182156 0.76341784]
 [0.89925988 0.64679544 0.81405398 0.8639188  0.27183229 0.53112839
  6.         0.28071156]
 [0.21828294 0.97125952 0.41999511 0.79552887 0.97345253 0.84001435
  0.54882495 0.28309142]]


## 1.4 Reshape the array to dimension [8, 3]
Can you think of multiple ways to do this?

[1 point]

In [5]:
data2=data1.copy()
data3=data1.copy()
data22=data2.T
print(data22)
print(" ")
print(" ")
data4=data3.reshape((8,3))
print(data4)

[[0.90066106 0.89925988 0.21828294]
 [0.47532933 0.64679544 0.97125952]
 [0.07441738 0.81405398 0.41999511]
 [0.09170602 0.8639188  0.79552887]
 [0.44569308 0.27183229 0.97345253]
 [0.0354568  0.53112839 0.84001435]
 [0.67182156 6.         0.54882495]
 [0.76341784 0.28071156 0.28309142]]
 
 
[[0.90066106 0.47532933 0.07441738]
 [0.09170602 0.44569308 0.0354568 ]
 [0.67182156 0.76341784 0.89925988]
 [0.64679544 0.81405398 0.8639188 ]
 [0.27183229 0.53112839 6.        ]
 [0.28071156 0.21828294 0.97125952]
 [0.41999511 0.79552887 0.97345253]
 [0.84001435 0.54882495 0.28309142]]


# 2. Numpy - Advanced

## 2.1 Create an array of integers ranging from 2 to 10
[1 point]

In [6]:
data21=np.arange(2,10)
print(data21)

[2 3 4 5 6 7 8 9]


## 2.2 Slice and Assign 
such that your array substitute all **even** (2, 4, 6 ...) values in the array with 0 (zero).

[1 point]

In [7]:
data21[::2]=0
print(data21)

[0 3 0 5 0 7 0 9]


## 2.3 Find all unique values in the modified array of section 2.2
[1 point]

In [8]:
np.unique(data21)

array([0, 3, 5, 7, 9])

# 3. Pandas

## 3.1 Create a Series with integers ranging from 5 to 10 with any index of your choice.
[1 point]

In [9]:
import pandas as pd
data31=pd.Series([i for i in range (5,10)])
print(data31)

0    5
1    6
2    7
3    8
4    9
dtype: int64


## 3.2 Print out all the entries in the Series defined in Section# 3.1 with value less than 7
[1 point]

In [10]:
data31.iloc[0:2]

0    5
1    6
dtype: int64

In [11]:
data31[data31<7]

0    5
1    6
dtype: int64

# 4. Pandas - Advanced

## 4.1 The following is the dataset created in a python *dict*

Convert it into a dataframe

[1 point]

In [12]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [13]:
data41=pd.DataFrame(data)
data41

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

## 4.2 Print out the first 3 enties in the dataframe created in Section# 4.1
[1 point]

In [14]:
data41.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

## 4.3 Sum the population size of all the entries
[1 point]

In [15]:
data41.sum()

state    OhioOhioOhioNevadaNevada
year                        10006
pop                          12.1
dtype: object

## 4.4 Remove all the entries with state: 'Nevada'
[1 point]

In [16]:
data41[data41['state']!='Nevada']

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

#5. Difference between 'Bar Chart' and a 'Histogram'

"Bar Chart" infers the discrete variables, while on the contrary "Histogram" infers the continuous variables.

# 6. Advantages of scatter plots?

It is used to find the two correlation between the two variables and it can easily show the relationship between the two variables.